### ISSUE TITLE
Problem with dependency torch-sparse

### ISSUE THREAD

**Issue by arne-vdb** [fratajcz/speos#1]
There was a problem after the install. When calling python training.py this error popped up:

> Tried to access nonexistent attribute or method 'crow_indices' of type 'Tensor'.:
>   File ".../miniconda3/envs/speos/lib/python3.7/site-packages/torch_sparse/tensor.py", line 109
>     def from_torch_sparse_csr_tensor(self, mat: torch.Tensor,
>                                      has_value: bool = True):
>         rowptr = mat.crow_indices()
>                  ~~~~~~~~~~~~~~~~ <--- HERE
>         col = mat.col_indices()

There seems to be a problem with the dependency torch_sparse. I used this command to download these packages before as stated in the documentation:

`pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric==2.0.4 -f https://data.pyg.org/whl/torch-1.8.2.0+11.6.html`

It succesfully installed torch_sparse, what could be the problem?

> Preparing metadata (setup.py) ... done
> Collecting torch-sparse
>   Downloading torch_sparse-0.6.16.tar.gz (208 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 208.2/208.2 kB 6.0 MB/s eta 0:00:00

**Comment by fratajcz** [comment]
Hi!

Thanks for the issue report. as it happens, `torch_sparse` has published a new version that isnt backward compatible with the pytorch version that is listed in the installation instruction. To alleviate the issue, deinstall `0.6.16`and install `0.6.12` afterwards:

```
pip uninstall torch-sparse
pip install torch-sparse==0.6.12
```

I will update the installation instructions. Did this fix the problem?

**Comment by arne-vdb** [comment]
Thanks for the quick feedback. That worked perfectly!
