### ISSUE TITLE
I meet a problem when running the outer_crossval.py script.

### ISSUE THREAD

**Issue by gsh150801** [fratajcz/speos#6]
![屏幕截图 2023-09-18 144708](https://github.com/fratajcz/speos/assets/33688592/55b5ee48-666c-4f38-a028-4d96d0a673d8)

**Comment by fratajcz** [comment]
Hi! This looks like the results have not been written to the appropriate files. Usually this comes from a missing flag in the config.

Check if your config has ```inference.save_tsv``` set to ```True```. 

You can check the example config for the crossvalidation ensemble in the [documentation](https://speos.readthedocs.io/en/latest/ensemble.html) on how to set that flag.

Please let me know if that worked.

**Comment by gsh150801** [comment]
This is my config file. I have set the inference.save_tsv to True. But it still didn't work.
![image](https://github.com/fratajcz/speos/assets/33688592/fbeebab1-7aaa-4774-aef9-e2f7650579a6)
The number of my label genes is about 20, I wonder if it causes the problem?

And this is my `mapping.json` under the `extensions` folder. 
![image](https://github.com/fratajcz/speos/assets/33688592/c9cce232-9382-4036-9542-01552e05d331)

I downloaded `AD.genes.out` from MAGMA and then removed the lines including genes in rat, mouse. I think the format of the `AD.genes.out` file is OK. So I wonder what's the reason?

**Comment by fratajcz** [comment]
Okay, then the config is not the problem. You can check the logfile `./logs/test_AD` for further Errors and Warnings, perhaps something went wrong in the data preprocessing or training. There you should also see if the 20 labeled genes were enough for training (i.e. if one of the training runs threw an error). 

If that yields no results and the training went smoothly you can manually check if the results were placed in the correct directory, there should be files in `./results/AD/` that look like `test_AD_outer_0_fold_1.tsv` for all 11 outer and 10 inner folds. 

Let me know if any of that helped.

BTW, i'd recommend finding more labelled genes. You can check OMIM or open target genetics, for example. However, if it is not possible to find more genes, then you can try reducing the `crossval.n_folds` count.

**Comment by fratajcz** [comment]
@gsh150801  We just identified an additional possible root cause for your problem. The postprocessor's loading path was not set to `config.inference.save_dir` but to `config.pp.save_dir`, causing the bug you experienced . Please set both save dirs to the same path (the one that previously was used as `config.inference.save_dir`) and the problem should go away. I will push a bugfix as soon as I get to it so seperate paths can be specified.

**Comment by gsh150801** [comment]
> @gsh150801 We just identified an additional possible root cause for your problem. The postprocessor's loading path was not set to `config.inference.save_dir` but to `config.pp.save_dir`, causing the bug you experienced . Please set both save dirs to the same path (the one that previously was used as `config.inference.save_dir`) and the problem should go away. I will push a bugfix as soon as I get to it so seperate paths can be specified.

This modification works.
